application: wator-test
version: www

runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /$
  static_files: static/index.html
  upload: static/index.html
- url: /(.*\.(html|js|css|png|jpg|jpeg))$
  static_files: static/\1
  upload: static/.*\.(html|js|css|png|jpg|jpeg)$

  